### ISSUE TITLE
The rate limiting doesn't appear to work.

### ISSUE THREAD

**Issue by GeoffThorpeFT** [Financial-Times/biz-ops-client#20]
The risk register runs at set of over 80 requests via a Promise.all() to an instance of this BizOpsClient (with default settings).
The result is a number of 'too many request' errors.

```
The server is listening on http://localhost:3456
assanka-database-archive 0
files-ft-com 7.919612985995368
error:  event=BIZ_OPS_QUERY_FAILED, error=Too Many Requests
(node:67999) UnhandledPromiseRejectionWarning: TooManyRequestsError: Too Many Requests
    at makeRequest (/Users/geoff.thorpe/Documents/Repos/risk-register/node_modules/@financial-times/biz-ops-client/lib/makeRequest.js:37:8)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.post (/Users/geoff.thorpe/Documents/Repos/risk-register/node_modules/@financial-times/biz-ops-client/lib/api/graphQL.js:83:18)
    at async bizOpsQuery (/Users/geoff.thorpe/Documents/Repos/risk-register/server/lib/bizOpsClient.js:32:18)
    at async calculateAndStoreRiskImpactScore (/Users/geoff.thorpe/Documents/Repos/risk-register/server/lib/rescoreRisks.js:9:15)
    at async Promise.all (index 67)
(node:67999) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:67999) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error:  event=BIZ_OPS_QUERY_FAILED, error=Too Many Requests
error:  event=BIZ_OPS_QUERY_FAILED, error=Too Many Requests
error:  event=BIZ_OPS_QUERY_FAILED, error=Too Many Requests
error:  event=BIZ_OPS_QUERY_FAILED, error=Too Many Requests
error:  event=BIZ_OPS_QUERY_FAILED, error=Too Many Requests
error:  event=BIZ_OPS_QUERY_FAILED, error=Too Many Requests
error:  event=BIZ_OPS_QUERY_FAILED, error=Too Many Requests
error:  event=BIZ_OPS_QUERY_FAILED, error=Too Many Requests
error:  event=BIZ_OPS_QUERY_FAILED, error=Too Many Requests
```

The code is visible in this branch/PR: https://github.com/Financial-Times/risk-register/pull/180

**Comment by i-like-robots** [comment]
For reference...

The library being used for rate limiting is `p-ratelimit` which I'm not very familiar with but it's implemented here: https://github.com/Financial-Times/biz-ops-client/blob/b4bd6783c90f6b1194fe864b2a4cf9549299b166/lib/internals.js#L18-L23

With items being added to the queue here: https://github.com/Financial-Times/biz-ops-client/blob/b4bd6783c90f6b1194fe864b2a4cf9549299b166/lib/createTransport.js#L44

**Comment by GeoffThorpeFT** [comment]
Silly me I was using an older version.  I have upgrade to v0.6.0. Thanks.
